---
AWSTemplateFormatVersion: "2010-09-09"

Parameters:
 BucketName:
  Description: S3 Bucket Name
  Type: String

Resources:
 S3Bucket:
  Type: AWS::S3::Bucket
  Description: Creating Amazon S3 bucket from CloudFormation
  Properties:
    BucketName: !Ref BucketName
      