---
AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Parameters:
 BucketName:
  Description: S3 Bucket Name
  Type: String


Resources:
 S3Bucket:
  Type: AWS::S3::Bucket
  Description: Creating Amazon S3 bucket from CloudFormation
  Properties:
    BucketName: !Ref BucketName
 
 

#  BucketPolicy:
#   Type: AWS::S3::BucketPolicy
#   Properties:
#     Bucket: !Ref BucketName
#     PolicyDocument: 
#       Version: "2012-10-17"
#       Statement:
#         - Effect: Allow
#           Principal: 
#             AWS: 'arn:aws:iam::268819417241:user/GautamSachdevaWatchguard'
#           Action:
#             - 's3:*'
#           Resource: 
#             - !Sub 'arn:aws:s3:::${BucketName}/*'
#             - !Sub 'arn:aws:s3:::${BucketName}'

 CrossAccountRole:
  Type: 'AWS::IAM::Role'
  Properties:
    AssumeRolePolicyDocument:
      Version: '2012-10-17'
      Statement:
      - Effect: 'Allow'
        Principal:
          AWS: arn:aws:iam::268819417241:root
        Action: 'sts:AssumeRole'
    Path: '/'
    Policies:
    - PolicyName: 'S3-ReadOnly'
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: 'Allow'
          Action:
          - 's3:Get*'
          - 's3:List*'
          Resource: '*'








