---
Parameters:
 BucketName:
  Description: S3 Bucket Name
  Type: String

Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Retain
    Properties:
      BucketName: !Fn Ref BucketName