---
Parameters:
 InstanceType:
  Type: String
  Default: t2.micro
  Description: Enter Type Of Instance-
 InsanceName:
  Description: S3 Bucket Name
  Type: String
    
Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-05502a22127df2492
      InstanceType: !Ref InstanceType
      Tags:
        - Key: Name
          Value: !Ref InstanceName

  