---
AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Parameters:
 InstanceType:
  Type: String
  Default: t2.micro
  Description: Enter Type Of Instance-

 InstanceName:
  Description: EC2 INSTANCE NAME
  Type: String

 BucketName:
  Description: S3 bucket Name
  Type: String

Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-05502a22127df2492
      InstanceType: !Ref InstanceType
      UserData:
       Fn::Base64: !Sub |
         #!/bin/bash
         sudo yum -y install httpd
         sudo service httpd start
      Tags:
        - Key: Name
          Value: !Ref InstanceName
  IamUser:
    Type: AWS::IAM::User
    Properties: 
      UserName: GautamSachdevaWatchguard

  IamPolicy:
    Type: AWS::IAM::Policy
    DependsOn: IamRole
    Properties:
      PolicyName: UserPolicy
      PolicyDocument: 
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal: 
            AWS: 'arn:aws:iam::868340526592:user/gautamAdmin'
            Action: 
              - 's3:*'
            Resource:
              - !Sub 'arn:aws:s3:::${BucketName}/*'
              - !Sub 'arn:aws:s3:::${BucketName}'
      Users:
       - !Ref IamUser