---
AWSTemplateFormatVersion: "2014-05-01"

Parameters:
 InstanceType:
  Type: String
  Default: t2.micro
  Description: Enter Type Of Instance-

 InstanceName:
  Description: EC2 INSTANCE NAME
  Type: String
  
Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-05502a22127df2492
      InstanceType: !Ref InstanceType
      Tags:
        - Key: Name
          Value: !Ref InstanceName

  IamPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: UserPolicy
      PolicyDocument: 
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action: 'sts:AssumeRole'
            Resource: !ImportValue MyIamRoleArn