---
AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Parameters:
 InstanceType:
  Type: String
  Default: t2.micro
  Description: Enter Type Of Instance-

 InstanceName:
  Description: EC2 INSTANCE NAME
  Type: String

 BucketName:
  Description: S3 bucket Name
  Type: String
 
 IamUsername:
  Description: Enter iam username
  Type: String

 SecurityGroupDescription:
  Description: Enter sg description
  Type: String

Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-05502a22127df2492
      InstanceType: !Ref InstanceType
      SecurityGroupIds: 
        - !Ref SecurityGroup
      UserData:
       Fn::Base64: !Sub |
         #!/bin/bash
         sudo yum -y install httpd
         sudo service httpd start
      Tags:
        - Key: Name
          Value: !Ref InstanceName

  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Ref SecurityGroupDescription
      SecurityGroupIngress: 
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
  IamUser:
    Type: AWS::IAM::User
    Properties: 
      UserName: !Ref IamUsername

  AssumeRolePolicy:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyName: 'AssumeRolePolicy'
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Action:
              - 'sts:AssumeRole'
            Resource: '*'
      Users:
        - !Ref IamUser

  CrossAccountRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: 'S3_Role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: 'Allow'
          Principal:
            AWS: 'arn:aws:iam::868340526592:root'
          Action: 'sts:AssumeRole'
      Path: '/'
      Policies:
      - PolicyName: 'EC2-Read'
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: 'Allow'
            Action:
            - "ec2:DescribeInstances"
            Resource: '*'